config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin,  skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root "homes#top"
  get "about" => 'homes#about'
  resources :items, only: [:index, :show]
end
namespace :admin do
  resources :genres, only: [:index,:create, :edit, :update]
  resources :items, except: :destroy
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name,presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :item_image
  def get_item_image(width,height)
    unless item_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_fill: [width, height], gravity: :center).processed
  end
  def tax_price
    (@item.price*1.1).floor
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genres = Genre.all
    @genre = Genre.new
  end
  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      flash[:notice] = "ジャンルを保存しました"
    redirect_to "/admin/genres"
    else
      render "/admin/index"
    end
  end
  def edit
    @genre = Genre.find(params[:id])
  end
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = ""
      redirect_to "/admin/genres"
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to "/admin/items"
  end
  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to "/admin/items"
  end

  private

  def item_params
    params.require(:item).permit(:name, :explation, :price, :sale_status, :genre_id, :item_image)
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row py-4">
    <h1>ジャンル編集</h1>
  </div>
  <%= form_with model: @genre, url: admin_genre_path(@genre.id),method: :patch, class: "row" do |f| %>
    <div class="form-group row col-9">
      <%= f.label :ジャンル名, class: "col-form-label col-sm-2" %>
      <%= f.text_field :name, class: "col-sm-3" %>
      <%= f.submit "変更を保存", class: "btn btn-success offset-1 col-sm-3" %>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row py-4">
    <h2>ジャンル一覧・追加</h1>
  </div>
  <%= form_with model: @genre, url: admin_genres_path,method: :post, class: "row" do |f| %>

    <div class="form-group row col-9">
      <%= f.label :ジャンル名, class: "col-form-label col-sm-2" %>
      <%= f.text_field :name, class: "col-sm-3" %>
      <%= f.submit "新規登録", class: "btn btn-success offset-1 col-sm-3" %>
    </div>
  <% end %>
  <div class="row mt-5">
    <div>
      <div class="row">
        <div class="col-6">ジャンル名</div>
        <div class="col-6"></div>
      </div>
      <div class="row">
        <% @genres.each do |genre| %>
          <div class="col-5 border-top py-2"><%= genre.name %></div>
          <div class="col-3 border-top py-2"><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn  btn-success" %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row my-3">
    <h2>商品編集</h2>
  </div>
  <div class="row d-flex justify-content-center mt-5">
     <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
    <div class="form-group row">
      <%= f.label :画像, class: "form_label col-4" %>
      <%= f.file_field :item_image, class: "col-8" %>
    </div>
    <div class="form-group row">
      <%= f.label :商品名, class: "form_label col-4" %>
      <%= f.text_field :name, class: "col-8 form_control" %>
    </div>
    <div class="form-group row">
      <%= f.label :商品説明, class: "form_label col-4" %>
      <%= f.text_area :explation, class: "form_control col-8" %>
    </div>
    <div class="form-group row">
      <%= f.label :値段, class: "form_label col-4" %>
      <%= f.text_field :price, class: "form_control col-7" %>　円
    </div>
    <div class="form-group row">
      <%= f.label :ジャンル, class: "form_label col-4" %>
      <%= f.select :genre_id,  options_from_collection_for_select(Genre.all, :id, :name), include_blank: '選択してください', class: "form-control col-md-8" %>
    </div>
    <div class="form-group">
      <%= f.label :販売ステータス, class: "form_label col4" %>
      <%= f.radio_button :sale_status,true, class: "col-1" %>
      <%= f.label :販売中, class: "col-3 form_label" %>
      <%= f.radio_button :sale_status,false, class: "col-1" %>
      <%= f.label :販売停止, class: "col-3 form_label" %>
    </div>
    <div class="text-center"><%= f.submit "変更を保存" ,class: "btn btn-success" %></div>
  <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="h2">商品一覧</div>
  </div>
  <div class="mt-5">
    <div class="row">
      <div class="col-1 ">id</div>
      <div class="col-4">商品名</div>
      <div class="col-2">値段</div>
      <div class="col-2">ジャンル</div>
      <div class="col-3">ステータス</div>
    </div>
    <div class="row">
      <% @items.each do |item| %>
        <div class="col-1"><%= item.id %></div>
        <div class="col-4"><%= link_to item.name, admin_item_path(item.id), class: "" %></div>
        <div class="col-2"><%= item.price %></div>
        <div class="col-2"><%= item.genre.name %></div>
        <div class="col-3"><%= item.sale_status %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row my-3">
    <h2>新規登録</h2>
  </div>
  <div class="row d-flex justify-content-center mt-5">
     <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <div class="form-group row">
      <%= f.label :画像, class: "form_label col-4" %>
      <%= f.file_field :item_image, class: "col-8" %>
    </div>
    <div class="form-group row">
      <%= f.label :商品名, class: "form_label col-4" %>
      <%= f.text_field :name, class: "col-8 form_control" %>
    </div>
    <div class="form-group row">
      <%= f.label :商品説明, class: "form_label col-4" %>
      <%= f.text_area :explation, class: "form_control col-8" %>
    </div>
    <div class="form-group row">
      <%= f.label :値段, class: "form_label col-4" %>
      <%= f.text_field :price, class: "form_control col-7" %>　円
    </div>
    <div class="form-group row">
      <%= f.label :ジャンル, class: "form_label col-4" %>
      <%= f.select :genre_id,  options_from_collection_for_select(Genre.all, :id, :name), include_blank: '選択してください', class: "form-control col-md-8" %>
    </div>
    <div class="form-group">
      <%= f.label :販売ステータス, class: "form_label col4" %>
      <%= f.radio_button :sale_status,true, class: "col-1" %>
      <%= f.label :販売中, class: "col-3 form_label" %>
      <%= f.radio_button :sale_status,false, class: "col-1" %>
      <%= f.label :販売停止, class: "col-3 form_label" %>
    </div>
    <div class="text-center"><%= f.submit "新規登録" ,class: "btn btn-success" %></div>
  <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row my-5">
    <h2>商品詳細</h2>
  </div>
  <div class="row mt-5">
    <div class="col-5">
      <%= image_tag @item.get_item_image(450,450) %>
    </div>
    <div class="col-6 offset-1">
      <div class="row my-4">
        <div class="col-4">商品名</div>
        <div class="col-8"><%= @item.name %></div>
      </div>
      <div class="row my-4">
        <div class="col-4">商品説明</div>
        <div class="col-8"><%= @item.explation %></div>
      </div>
      <div class="row my-4">
        <div class="col-4">税抜き値段<br>(税抜き価格)</div>
        <div class="col-8"><%= @item.price %>(<%=  (@item.price*1.1).floor %>)円</div>
      </div>
      <div class="row my-4">
        <div class="col-4">ジャンル</div>
        <div class="col-8"><%= @item.genre.name %></div>
      </div>
      <div class="row my-4">
        <div class="col-4">販売ステータス</div>
        <div class="col-8 text-success"><%= @item.sale_status %></div>
      </div>
      <div class="ml-5"><%= link_to "編集をする", edit_admin_item_path(@item.id), class: "btn btn-success" %></div>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
      <%= link_to root_path do %>
        <!--<#%= image_tag 'nagano_cake_logo.png', size: '150x90', class: "navbar-brand" %>-->
      <% end %>
      <% if customer_signed_in? %>
        <h6 class="text-dark">ようこそ、<%= current_customer.last_name %>さん！</h6>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
            <li class="nav-item btn">
              <%= link_to "マイページ", customers_my_page_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "カート", cart_items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
          <% else %>
            <li class="nav-item btn">
              <%= link_to "About", about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item btn">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>